[project]
name = "colorings"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gurobipy>=12.0.3",
    "numpy>=2.3.2",
    "scipy>=1.16.1",
]
